# Render.com deployment configuration
# render.yaml - Place this in your repository root

services:
  - type: web
    name: chatbot-rag
    env: docker
    plan: starter  # or a paid plan for better performance
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HF_HOME
        value: /home/appuser/.cache/huggingface
      - key: TRANSFORMERS_CACHE
        value: /home/appuser/.cache/huggingface/transformers
      - key: HF_DATASETS_CACHE
        value: /home/appuser/.cache/huggingface/datasets
      - key: PRELOAD_MODEL
        value: false
      # Add your API keys here
      - key: GROQ_API_KEY
        sync: false  # Set this in Render dashboard for security
    buildCommand: docker build -t chatbot-rag .
    startCommand: docker run -p 10000:8000 chatbot-rag
    healthCheckPath: /health